(fix) Fix submit button loading state
openmrs/openmrs-esm-form-engine-lib pull request #439
Opened 2024-12-04 12:39 UTC by denniskigen

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Fixes an issue with the submit button not being disabled when the form is being submitted. Also tweaks the inline loading indicator shown in the button so that it doesn't take up extra vertical space.

## Screenshots

## Related Issue

## Other

2024-12-05 15:20 UTC, ibacher approved these changes

2024-12-09 11:38 UTC, samuelmale requested changes
@denniskigen You probably want to update the sidebar: https://github.com/openmrs/openmrs-esm-form-engine-lib/blob/main/src/components/sidebar/sidebar.component.tsx#L63-L74

2024-12-09 11:38 UTC, samuelmale commented on src/form-engine.component.tsx
> +                      disabled={isLoadingDependencies || !isSubmitting || mode === 'view'}
Fix the failing tests by:

```suggestion
                      disabled={isLoadingDependencies || isSubmitting || mode === 'view'}
```

2024-12-10 09:01 UTC, samuelmale approved these changes

2024-12-10 09:04 UTC, merged

2024-12-10 09:30 UTC, denniskigen commented
Thanks for the reviews!